#! /usr/bin/env perl

use 5.10.0;
use strict;

my %workers;
my @debugs = <worker*debug>;
my @failures = <makeflow.failed.*\/worker*debug>;
@debugs = (@debugs, @failures);

foreach my $debug (@debugs) {
    my $task;
    if($debug =~ m/worker.(?<task>\d+).debug/) {
        $task = $+{task};
    }
    my $worker;
    my $addr;
    my $port;
    
    open(DEBUG, $debug);
    while(my $line = <DEBUG>) {
        if($worker) {
            last;
        }

        #wq: connected to master 10.32.74.140:9000 via local address 10.32.74.164:36500
        elsif($line =~ m/wq: connected to master \S+ via local address \S+:(?<port>\d+)/) {
            $port = $+{port};
            next;
        }

        #dns: finding my hostname: uname = disc13.crc.nd.edu, address = 10.32.74.164, hostname = disc13.crc.nd.edu
        elsif($line =~ m/dns: finding my hostname: uname = \S+, address = \S+, hostname = (?<addr>\S+)/) {
            $addr = $+{addr};
            $worker = "$addr:$port";
            next;
        }
    }
    close(DEBUG);

    if(exists $workers{$worker} and $task > $workers{$worker}) {
        printf(STDERR "Unlinking previous file worker.$workers{$worker}.debug.\n");
        my $result = unlink("worker.$workers{$worker}.debug");
        if(!$result) {
            printf(STDERR "Unlinking previous file makeflow.failed.$workers{$worker}/worker.$workers{$worker}.debug.\n");
            unlink("makeflow.failed.$workers{$worker}/worker.$workers{$worker}.debug");
        }
        $workers{$worker} = $task;
    }
    elsif(exists $workers{$worker} and $task < $workers{$worker}) {
        printf(STDERR "Unlinking current file $debug.\n");
        unlink($debug); 
    }
    else {
        $workers{$worker} = $task;
    }
}

exit(0);

# vim: tabstop=8 shiftwidth=4 softtabstop=4 expandtab shiftround autoindent
