#!/bin/sh

source /afs/crc.nd.edu/group/ccl/software/cclsetup.sh

cclimport ltrace current

ltrace -f -r -s 256 -o ltrace.debug -e *open*+*stat*+*getenv*+*setenv* $@ && cp ../../worker.debug .

echo "Wrote an ltrace for command: \"$@\" with PID $$ from PPID $PPID" >> ltrace.debug

exit 1
