#!/bin/sh

source /afs/crc.nd.edu/group/ccl/software/cclsetup.sh

cclimport ltrace current

ltrace -f -r -s 4096 -o ltrace.debug -e *open*+*stat*+*getenv*+*setenv* $@ && cp ../../worker.debug .

result=$(grep "+++ exited" ltrace.debug | awk '{print $6}' | cut -d ")" -f 1)
hostname=$(hostname -f)

echo "Wrote an ltrace for command: \"$@\" with PID $$ from PPID $PPID on $hostname" >> ltrace.debug

printenv >> ltrace.debug

exit $result
